# Generated by Django 2.2.28 on 2023-04-03 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('idIngredient', models.BigAutoField(primary_key=True, serialize=False)),
                ('nomIngredient', models.CharField(max_length=50, verbose_name='le nom de cet ingrédient ')),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('idPizza', models.BigAutoField(primary_key=True, serialize=False)),
                ('nomPizza', models.CharField(max_length=50, verbose_name='le nom de cette pizza ')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='le prix ')),
            ],
        ),
    ]
